### ISSUE TITLE
After logging into FB, nothing happens

### ISSUE THREAD

**Issue by camerondwills** [signalpoint/facebook#2]
Hello,

I've followed the read-me exactly. The continue with facebook button shows up, and I can successfully log into facebook and connect to my FB app. However, once I do this, the apps login page then says "Loading" and nothing happens. Logcat shows these messages:

CordovaLog﹕ file:///android_asset/www/cordova.js: Line 1060 : processMessage failed: Stack: ReferenceError: loginWindow_loadStopHandler is not defined
"POST: http://www.mysite.com/?q=drupalgap/fboauth/connect.json - 401 - Unauthorized", source: file:///android_asset/www/jdrupal-7.x-1.2.min.js (32)
CordovaLog﹕ file:///android_asset/www/jdrupal-7.x-1.2.min.js: Line 32 : ["The username  has not been activated or is blocked."]

**Comment by signalpoint** [comment]
@WillsCreative Did you patch the services_fboauth module? https://www.drupal.org/node/2376345

Make sure that `Visitors` can register accounts (without admin approval), and that `Require e-mail verification when a visitor creates an account.` is _not_ checked under `admin/config/people/accounts`.

**Comment by camerondwills** [comment]
@signalpoint I can confirm my services_fboauth module is patched, and that visitors are enabled to create accounts with admin approval. Is there some special setting in the FBoAuth module or facebook developer app settings that needs to be set that isn't mentioned in the readme? 

![capture](https://cloud.githubusercontent.com/assets/12927636/8225019/4577d942-1544-11e5-9ad1-86975fb10187.JPG)

**Comment by signalpoint** [comment]
@WillsCreative thank you for confirming. No I don't think there is any special setting outside of Drupal. From the error message `The username has not been activated or is blocked.`, it seems the user account hasn't been activated yet. What other module(s) do you have installed that are part of the login/registration process? i.e. Login Toboggon, etc...?

**Comment by camerondwills** [comment]
@signalpoint I'm using the Login Toboggon modules on both my drupal site and the drupalgap module. I also have reCAPTCHA enabled on user registration but I've installed and successfully setup a captcha override module for drupalgap per the documentation so it's not needed when registering via drupalgap

**Comment by signalpoint** [comment]
@WillsCreative try disabling the LT module, and then see if that fixes it.

**Comment by camerondwills** [comment]
@signalpoint I disabled LT on both my website and removed the phonegap module, and still the same error :/

**Comment by camerondwills** [comment]
I checked my site logs and filtered to fboauth. I noticed right after trying to connect facebook, a message appears saying "Email address not provided by Facebook." pointing to ?q=drupalgap/fboauth/connect.json

**Comment by signalpoint** [comment]
@WillsCreative it sounds like your "facebook" app isn't configured properly to expose a facebook user's e-mail address. I'd recommend taking up this issue with the https://www.drupal.org/project/fboauth project, as they are in charge of that particular error message:

```
./includes/fboauth.fboauth.inc:312:    watchdog('fboauth', 'Email address not provided by Facebook.');
```

**Comment by Perfectbit74** [comment]
Hi,
I had found some errors and i made this forks:
- in facebook.js I added at line 97 "if(typeof token!='undefined') " because every time the system was looking for token undefined and broken all...
- at line 83 I changed   facebook_connected(response.authResponse.accessToken); because the object returned from facebook has accessToken not token field.
  Now it works perfectly.
  I spent 5 days to find this bug...

**Comment by signalpoint** [comment]
@Perfectbit74 I'm sorry to hear you had troubles with this, I've always struggled with FB related issues as well. Thank you for reporting the fixes that worked for you. Did you also need to use `accessToken` instead of `token` on this line too? https://github.com/signalpoint/facebook/blob/7.x-1.x/facebook.js#L27

**Comment by Perfectbit74** [comment]
At line 27 no because loginStatus.authResponse.token is managed from the system...while response.authResponse.accessToken is generated from the facebook json result :)

**Comment by Perfectbit74** [comment]
Hi Tyler,here the app developed with drupalgap for voting at Skepto International Film Festival 2016:
https://play.google.com/store/apps/details?id=com.netsoulsrl&hl=it
Thank you very much!
Mauro

Date: Fri, 18 Mar 2016 05:34:35 -0700

**Comment by signalpoint** [comment]
@Perfectbit74 That's great news, thank you for sharing! Please submit your app to the DrupalGap listing if you'd be so kind: http://drupalgap.org/apps
