### ISSUE TITLE
facebook login problems

### ISSUE THREAD

**Issue by coolman7** [signalpoint/facebook#3]
I followed all instruction except 2:

1) If set the "Valid OAuth redirect URIs" to: https://www.facebook.com/connect/login_success.html
fb oauth from drupal website cannot make connection with facebook. So I did not change Valid OAuth redirect URL.

2) I downloaded openfb.js from link provided in documentation. But I noticed patches already applied and code changed somewhat. So I did not change anything from openfb.js

So the result is: When I click to Connect with Facebook link at mobile app, it returns this error: 

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

Any idea what's wrong?

**Comment by signalpoint** [comment]
@coolman7 nope, I'm not sure what is going on there. I'd recommend looking through the various issues in https://github.com/ccoenraets/OpenFB/issues, as I recall coming across the same issue (plus many others) when trying to get this to work for an app.

**Comment by mkinnan** [comment]
Had the same trouble ... you need to have 2 URLs in the field ...

![facebook-settings](https://cloud.githubusercontent.com/assets/13283396/9155409/f8baa92c-3e74-11e5-9edc-487589fc6418.png)
